### PR TITLE
Doc cleanup

### PR DESCRIPTION
**Pull request by adefee**

### CODE REVIEW

**Comment by manifestcyber** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/manifest/sbom-transmitter?version=dev:877fafa363914903350041b7af8a49f5e6526665

**Review by marcelolima381 — APPROVED** [review]

**Comment by manifestcyber** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/manifest/sbom-transmitter?version=dev:e27bcb91736fe56f732522200070a5b576236398

**Comment by manifestcyber** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/manifest/sbom-transmitter?version=dev:e27bcb91736fe56f732522200070a5b576236398

**Comment by manifestcyber** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/manifest/sbom-transmitter?version=0.2.7

**Pull request merged**
