### PR TITLE
fix: spdx update script

### PR DESCRIPTION
**Pull request by manifestori**

### CODE REVIEW

**Comment by manifestcyber** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/manifest/sbom-transmitter?version=dev:43672d130fa5fc906351ff6779020dc098fbfa7f

**Review by adefee — APPROVED** [review]

**Comment by manifestcyber** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/manifest/sbom-transmitter?version=dev:93ccb71683cfc937aaf4183a9518f30cedd377f5

**Comment by manifestcyber** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/manifest/sbom-transmitter?version=dev:574f3dc724571da9b30f99195c51198357adba4d

**Comment by manifestcyber** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/manifest/sbom-transmitter?version=dev:574f3dc724571da9b30f99195c51198357adba4d

**Comment by manifestcyber** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/manifest/sbom-transmitter?version=0.2.6

**Comment by manifestcyber** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/manifest/sbom-transmitter?version=dev:574f3dc724571da9b30f99195c51198357adba4d

**Pull request merged**
